require(File.join(File.dirname(__FILE__), 'config', 'boot'))
require 'codex/rake/codextask'

Codex::Rake::CodexTask.new do |c|
  # c.content_dir = 'content'
  # c.output_dir  = 'html'
  # c.metadata    = "#{c.content_dir}/metadata.yml"
end